[workspace]
members = ["web", "embedded"]
resolver = "2"

[package]
name = "application"
version = "0.1.0"
edition = "2021"
description = "Template for starting a Yew project using Trunk"
license = "MIT OR Apache-2.0"

[dependencies]
embedded-graphics = "0.7.0"
embedded-graphics-core = "0.3.3"
embedded-hal = "1.0.0-rc.1"
embedded-hal-bus = "0.1.0-rc.1"
hash32 = "0.2.1"
heapless = "0.7.16"
num_enum = { version = "0.7.1", default-features = false }
defmt = { version = "0.3", optional = true }

[features]
embedded = ["dep:defmt"]
