[package]
name = "red_screen"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics-core = { version = "0.3" }
embedded-hal = { version = "1.0.0-rc.1" }
ili9488 = { path = "../ili9488" }
xpt2046 = { path = "../xpt2046" }
touchscreen = { path = "../touchscreen" }
