name: pr_check

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: cargo fmt --check --all
    - name: Clippy
      run: cargo clippy -- -D clippy-pedantic
    - name: Test
      run: cargo test --all
#    - name: install toolchain
#      uses: actions-rs/toolchain@v1
#      with:
#        toolchain: stable
#        target: wasm32-unknown-unknown
#        override: true
#        profile: minimal
#    - name: Install trunk
#      uses: jetli/trunk-action@v0.1.0
#      with:
#        version: 'latest'
#    - name: Build
#      run: trunk build
